'use client';
import { useEffect, useState } from 'react';
import { PaperDownloads } from './paper-downloads';
type Brief = { id: number; summary: string; published_at: number };
export function LatestBrief() {
  const [edition,setEdition] = useState<{ id: number; summary: string; published_at: number }|null>(null);
  const [scientificId,setScientificId] = useState<number|null>(null);
  const [scientificAbstract,setScientificAbstract] = useState('');
  const [researchUpdate,setResearchUpdate] = useState<{ findingsSoFar: string; researchDirections: string; nextSteps: string } | null>(null);
  const [error,setError] = useState(false);
  useEffect(()=>{let active=true;const refresh=async()=>{try{const [r,s]=await Promise.all([fetch('/api/papers',{cache:'no-store'}),fetch('/api/scientific-paper',{cache:'no-store'})]);if(!r.ok)throw Error();const d=await r.json() as { editions: Brief[] };const p=s.ok ? await s.json() as { paper?: { editionId: number; abstract: string; findingsSoFar: string; researchDirections: string; nextSteps: string } } : null;if(active){setEdition(d.editions[0]??null);setScientificId(p?.paper?.editionId??null);setScientificAbstract(p?.paper?.abstract??'');setResearchUpdate(p?.paper ? { findingsSoFar:p.paper.findingsSoFar,researchDirections:p.paper.researchDirections,nextSteps:p.paper.nextSteps } : null);setError(false);}}catch{if(active)setError(true);}};void refresh();const t=setInterval(()=>void refresh(),60000);return()=>{active=false;clearInterval(t);};},[]);
  return <section className="mb-8 rounded-2xl border border-pink-200 bg-pink-50 p-6 text-rose-950"><p className="text-sm font-medium">THREE-HOUR RESEARCH PAPERS</p><h2 className="mt-3 font-serif text-3xl">Read the findings. Trace the evidence.</h2><p className="mt-4 leading-7">{scientificId!==null ? scientificAbstract : edition?.summary ?? (error ? 'The publication feed is temporarily unavailable.' : 'The first evidence snapshot is awaiting publication.')}</p><p className="mt-3 text-sm">{scientificId!==null ? `Latest checked paper: edition ${scientificId}.` : 'Scientific synthesis is in source and attribution review.'}{edition && edition.id!==scientificId ? ` Newest frozen source edition ${edition.id} is available for inspection.` : ''} AI review is not journal peer review.</p>{researchUpdate && <div className="mt-5 grid gap-3 md:grid-cols-3">{[['Findings so far',researchUpdate.findingsSoFar],['Research directions',researchUpdate.researchDirections],['What happens next',researchUpdate.nextSteps]].map(([title,body])=><div key={title} className="rounded-xl border border-pink-200 bg-white p-4"><h3 className="font-semibold">{title}</h3><p className="mt-2 line-clamp-5 text-sm leading-6">{body}</p></div>)}</div>}{edition && <PaperDownloads id={scientificId??edition.id} scientificReady={scientificId!==null} />}<div className="mt-5 flex flex-wrap gap-5 text-sm font-medium underline">{scientificId!==null && <a href={'/papers/'+scientificId+'/scientific'}>Read latest scientific paper</a>}{edition && <a href={'/papers/'+edition.id}>Source edition {edition.id}</a>}<a href="/papers">All editions</a></div></section>;
}
