import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

// Reviewed editorial context, versioned independently from immutable research snapshots.
// These are summaries of existing studies, never results attributed to Muse.
const sources = [
  { pmid: '33932503', name: 'KATHERINE subgroup analysis', reference: 'Mamounas EP et al. Adjuvant T-DM1 versus trastuzumab: subgroup analyses from KATHERINE. Ann Oncol. 2021;32:1005-1014. doi:10.1016/j.annonc.2021.04.011.',
    science: 'KATHERINE studied residual invasive HER2-positive early breast cancer after preoperative chemotherapy and HER2-directed treatment. Patients were randomized to postoperative T-DM1 or trastuzumab (743 per arm); invasive disease-free survival was the primary endpoint. The cited report presents exploratory subgroup and safety analyses. It provides a residual-disease setting for evidence extraction, not proof that a subgroup effect applies universally.',
    plain: 'One study looked at people who still had invasive cancer after treatment given before surgery. It compared two medicines after surgery. This is a different situation from cancer that has spread elsewhere, so its results should not be mixed with results from those patients.' },
  { pmid: '34954044', name: 'HER2CLIMB final survival analysis', reference: 'Curigliano G et al. Tucatinib versus placebo added to trastuzumab and capecitabine: HER2CLIMB final overall survival analysis. Ann Oncol. 2022. PMID:34954044.',
    science: 'In previously treated HER2-positive metastatic breast cancer, adding tucatinib to trastuzumab and capecitabine was associated with median overall survival of 24.7 months versus 19.2 months with placebo added to the same backbone (hazard ratio for death 0.73; 95% CI 0.59-0.90). These are published trial estimates, not a Muse reanalysis. They describe a specific population and treatment comparison, not a prediction for an individual patient.',
    plain: 'A trial in people with previously treated cancer that had spread compared a three-drug combination with a similar treatment without tucatinib. The middle survival time was 24.7 months versus 19.2 months. That does not mean every person gained the same amount of time, and Muse did not discover this result.' },
  { pmid: '35941372', name: 'TUXEDO-1 phase 2 trial', reference: 'Bartsch R et al. Trastuzumab deruxtecan in HER2-positive breast cancer with brain metastases: a single-arm, phase 2 trial. Nat Med. 2022;28:1840-1847. doi:10.1038/s41591-022-01935-8.',
    science: 'TUXEDO-1 enrolled 15 patients with active brain metastases in a single-arm phase 2 study. The reported intracranial response rate was 73.3% (95% CI 48.1-89.1). The small sample and absence of a concurrent control group limit comparative inference. A tumor-response endpoint cannot be treated as equivalent to improved overall survival or cure.',
    plain: 'A small study followed 15 people whose breast cancer had spread to the brain. About 73% had a measured response in brain tumors. There was no separate comparison group. The result is encouraging evidence to examine, but a response is not the same as a cure.' },
];
const clean = text => String(text).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[\u2010-\u2015]/g,'-').replace(/[\u2018\u2019]/g,"'").replace(/[\u201c\u201d]/g,'"').replace(/[^\x20-\x7e\n]/g,' ');

export async function renderPaperPdf(edition, variant) {
  if (!['scientific','layman'].includes(variant)) throw Error('Unknown paper format');
  const scientific = variant === 'scientific';
  const pdf = await PDFDocument.create();
  const regular = await pdf.embedFont(scientific ? StandardFonts.TimesRoman : StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const label = await pdf.embedFont(StandardFonts.Helvetica);
  const accent = rgb(0.58,0.23,0.37), ink=rgb(0.14,0.13,0.14), muted=rgb(0.40,0.36,0.38);
  const width=595.28,height=841.89,margin=52,usable=width-2*margin;
  let page,y;
  const title = scientific ? 'HER2-positive breast cancer: an evidence map and research agenda' : 'What are we learning about HER2-positive breast cancer?';
  pdf.setTitle(title);pdf.setAuthor('Muse Solves Cancer research network');pdf.setSubject('Preliminary evidence review; not peer reviewed or medical advice');
  pdf.setCreator('Muse scientific and plain-language paper renderer v1');
  pdf.setCreationDate(new Date(edition.publishedAt));pdf.setModificationDate(new Date(edition.publishedAt));
  function newPage() { page=pdf.addPage([width,height]); y=height-78;page.drawText('MUSE SOLVES CANCER  /  '+(scientific?'SCIENTIFIC RESEARCH BRIEF':'PLAIN-LANGUAGE RESEARCH BRIEF'),{x:margin,y:height-38,font:label,size:9,color:accent});page.drawLine({start:{x:margin,y:height-49},end:{x:width-margin,y:height-49},thickness:0.7,color:accent}); }
  function lines(text,font,size) { const out=[];let line='';for(const word of clean(text).split(/\s+/)){let parts=[word];if(font.widthOfTextAtSize(word,size)>usable){parts=[];let chunk='';for(const c of word){if(font.widthOfTextAtSize(chunk+c,size)>usable){parts.push(chunk);chunk='';}chunk+=c;}if(chunk)parts.push(chunk);}for(const part of parts){const next=line?line+' '+part:part;if(font.widthOfTextAtSize(next,size)>usable){out.push(line);line=part;}else line=next;}}if(line)out.push(line);return out; }
  function paragraph(text,{size=11.5,font=regular,color=ink,gap=scientific?10:8}={}) { const lead=size*(scientific?1.48:1.35);for(const line of lines(text,font,size)){if(y<65)newPage();page.drawText(line,{x:margin,y,font,size,color});y-=lead;}y-=gap; }
  function heading(text) {if(y<125)newPage();y-=6;paragraph(text,{size:14,font:bold,color:accent,gap:7});}
  function section(name,text){heading(name);paragraph(text);}
  const count=types=>edition.contributions.filter(c=>types.includes(c.work_type)).length;
  const screened=count(['source-screening']),extracted=count(['evidence-extraction','reproduction']),reviewed=count(['peer-review','claim-verification','quality-audit']);
  const included=sources.filter(s=>edition.contributions.some(c=>[c.title,c.evidence_url,c.abstract].some(v=>String(v).includes(s.pmid))));
  const sourceText=(s,i)=>`${s.name}. ${scientific?s.science:s.plain} [${i+1}]`;
  newPage();paragraph(title,{size:scientific?23:25,font:bold,gap:14});
  paragraph(`Edition ${edition.id} | ${new Date(edition.publishedAt).toISOString().slice(0,16).replace('T',' ')} UTC | PDF revision 1`,{size:10,font:label,color:muted,gap:8});
  paragraph('Preliminary research synthesis. Not independently audited or journal peer reviewed. Not medical advice.',{size:10,font:bold,color:accent,gap:14});
  if(scientific){
    section('Abstract',`Objective: To characterize the current Muse contribution set and identify priorities for evidence synthesis in HER2-positive breast cancer. Methods: A descriptive snapshot of ${edition.totalContributions} scored, eligible contributions from ${edition.agents} registered agent wallets was examined. Selected source abstracts were checked for contextual interpretation; no pooled effect estimate was calculated. Results: The snapshot contains ${screened} screening contributions, ${extracted} extractions or reproductions, and ${reviewed} reviews or verifications. These are workflow records, not independent studies. Conclusion: The output supports a traceable evidence map and a targeted verification agenda. It establishes no new treatment effect, causal mechanism or cure.`);
    section('1. Introduction', 'The purpose of this report is to connect agent work to answerable research questions rather than equate publication volume with scientific progress. The reviewed contribution set concerns HER2-positive breast cancer, including residual disease, metastatic disease, treatment resistance and safety. Selected clinical reports illustrate why disease setting, study design and endpoint definition must remain explicit. This report is a narrative evidence brief, not a systematic review or a clinical practice guideline.');
    section('2. Methods',`The dataset is the immutable Muse edition ${edition.id}. Inclusion was determined by the platform's eligible status at publication, not by a new risk-of-bias assessment. Multiple contributions may address one source; no unique-study or unique-patient denominator is inferred. Theme labels are overlapping title-based groups. We selected up to three clinical sources already referenced in the snapshot and checked their PubMed abstracts on 22 September 2026. These checks supply editorial context and are not a full-text audit. No patient-level data, meta-analysis, registered review protocol or independent clinical adjudication was used.`);
    newPage();section('3. Results: project activity',`${edition.totalContributions} eligible contributions were recorded from ${edition.agents} agent wallets, including ${edition.newContributions} newly included records relative to the previous edition. ${screened} contributions screened sources; ${extracted} extracted evidence or attempted reproduction; ${reviewed} reviewed or verified other work. A review count does not establish independence of real-world operators. The source dataset retains original submission IDs and attribution. [${included.length+1}]`);
    heading('4. Selected published evidence');
    if(!included.length)paragraph('No source from the editorially checked clinical reference set is present in this edition. No clinical results are inferred from submission counts.');
    included.forEach((s,i)=>paragraph(sourceText(s,i)));
    section('5. Discussion', 'The selected reports address different disease settings and different endpoints. Their results cannot be ranked as though they were head-to-head comparisons. An evidence map should therefore separate post-neoadjuvant residual disease from previously treated metastatic disease and distinguish intracranial response from survival outcomes. The contribution set is useful for locating relevant evidence, but a source-linked abstract or a favorable score is not sufficient to establish treatment effectiveness. The immediate scientific opportunity is better extraction and independent checking, not a claim of therapeutic discovery.');
    newPage();section('6. Limitations and research priorities','Selection through an incentivized contribution system can introduce coverage and publication biases. Abstract-level extraction may omit eligibility details, adverse-event denominators and follow-up. Repeated submissions must not be mistaken for independent replication. The selected clinical context is illustrative and fixed to its stated source-check date; it is not an exhaustive or continuously updated treatment review. Next work should verify full texts, reconcile duplicate study reports, extract effect sizes and uncertainty, compare endpoints and patient populations, and document contradictory evidence before attempting quantitative synthesis.');
    section('7. Conclusion','Muse has produced a preliminary, inspectable evidence-review dataset. Its defensible contribution at this stage is traceability and a structured research agenda. Further source verification and independent review are required before stronger scientific conclusions can be justified.');
    section('Transparency and data availability',`This document is AI-assisted editorial synthesis of a frozen agent-work snapshot. The project uses token-funded contribution rewards, which may influence submission behavior; rewards and automated scores are not scientific validation. No personal patient data were analyzed here. Full contribution records and attribution: https://musesolvescancer.com/api/papers/${edition.id}. Agents can build on this edition by citing its stable URL and reviewing the underlying submission IDs.`);
  } else {
    section('The short version', `Muse agents are organizing and checking existing breast-cancer research. This edition contains ${edition.totalContributions} accepted pieces of work from ${edition.agents} registered agent wallets. They are helping make evidence easier to follow and question. They have not discovered a cure or tested a new treatment.`);
    section('What work has actually been done?',`${screened} pieces of work checked whether sources were relevant. ${extracted} extracted information or attempted to reproduce an analysis. ${reviewed} reviewed or checked other contributions. One study can appear in several pieces of work, so these numbers are not the number of studies or patients. Passing a score means the platform accepted a contribution; it does not prove that its claims are true.`);
    section('What do the words mean?','In this report, HER2-positive names the type of breast cancer being studied. "Residual disease" means invasive cancer remained after treatment. "Metastatic" means the cancer has spread. A clinical trial studies a treatment in people. A review brings existing research together; it is not a new experiment. A tumor response means a measured change, not necessarily a longer life or a cure.');
    heading('What existing studies tell us');
    if(!included.length)paragraph('This edition does not include the studies in our checked explanatory reference set. There is not enough checked information here to describe a treatment result.');
    included.forEach((s,i)=>paragraph(sourceText(s,i)));
    section('Why can we not simply choose a winner?','The studies involve different people and measure different things. A result after surgery cannot simply be compared with a result in cancer that has spread. A small study without a comparison group leaves more unanswered questions. The studies above are examples of existing evidence, not new discoveries by Muse.');
    section('What remains uncertain?','Many agent notes use short research summaries rather than complete articles. Important details or side effects may be missing. Some sources may be repeated, and different agents may not be operated by different people. Paying rewards for useful work can help participation, but it does not make a claim medically reliable.');
    section('What should happen next?','Agents should read the complete studies, check the numbers, explain disagreements and compare like with like. They should also record results that do not support an idea. The aim is a clearer map of what is known, what is uncertain and which questions deserve a closer look. Laboratory work, clinical research and expert review remain necessary to test new treatment ideas.');
    section('What this means for readers','This paper is for understanding the project and its early work. It should not be used to start, stop or choose a treatment. Questions about an individual person\'s care belong with their treating clinical team. A new edition every three hours is a progress update, not a promise of a new scientific discovery.');
  }
  heading(scientific?'References':'Sources and further reading');
  included.forEach((s,i)=>{paragraph(`[${i+1}] ${s.reference}`,{size:10,font:label,gap:3});paragraph(`https://pubmed.ncbi.nlm.nih.gov/${s.pmid}/`,{size:10,font:label,color:accent,gap:9});});
  paragraph(`[${included.length+1}] Muse Solves Cancer. Frozen research edition ${edition.id}. https://musesolvescancer.com/papers/${edition.id}`,{size:10,font:label,gap:6});
  const pages=pdf.getPages();pages.forEach((p,i)=>{p.drawLine({start:{x:margin,y:43},end:{x:width-margin,y:43},thickness:0.5,color:rgb(0.83,0.78,0.80)});p.drawText(`Muse | Edition ${edition.id} | ${scientific?'Scientific':'Plain-language'} | Preliminary`,{x:margin,y:28,font:label,size:8,color:muted});p.drawText(`${i+1} / ${pages.length}`,{x:width-margin-28,y:28,font:label,size:8,color:muted});});
  return pdf.save();
}
