import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getScientificPaper } from '@/lib/scientific-paper';

export const dynamic = 'force-dynamic';
export const metadata = { title: 'Scientific research paper · Muse Solves Cancer' };

export default async function ScientificPaperPage({ params }: { params: Promise<{ id: string }> }) {
  const id = Number((await params).id);
  if (!Number.isSafeInteger(id) || id < 0) notFound();
  const paper = await getScientificPaper(id);
  if (!paper) return <main className="mx-auto max-w-3xl px-5 py-12"><Link href="/papers" className="text-primary underline">Research archive</Link><h1 className="mt-8 font-serif text-4xl">Scientific paper in verification</h1><p className="mt-4 leading-7">The three-hour evidence snapshot is available. The scientific synthesis will appear here after its independent model check passes.</p><Link href={'/papers/'+id} className="mt-6 inline-block text-primary underline">Read the frozen source edition</Link></main>;
  const attribution = new Map(paper.attribution.map(item => [item.id, item]));
  const section = (title: string, body: string) => <section className="mt-10"><h2 className="font-serif text-2xl">{title}</h2><p className="mt-4 whitespace-pre-wrap leading-8">{body}</p></section>;
  return <main className="mx-auto max-w-4xl px-5 py-10 text-foreground"><nav className="flex flex-wrap gap-5 text-sm print:hidden"><Link href="/">Muse</Link><Link href="/papers">All papers</Link><Link href={'/papers/'+id}>Source edition</Link><a download href={'/api/papers/'+id+'/scientific/pdf'} className="font-semibold text-primary underline">Download PDF</a></nav><article><p className="mt-12 font-mono text-xs uppercase tracking-widest text-primary">Scientific research synthesis · Edition {id}</p><h1 className="mt-4 font-serif text-4xl leading-tight">{paper.title}</h1><p className="mt-5 text-sm text-muted-foreground">{new Date(paper.publishedAt).toUTCString()} · AI-assisted synthesis · Independent model source check</p><p className="mt-5 rounded-xl border border-pink-200 bg-pink-50 p-4 text-sm leading-6 text-rose-900">{paper.review} Source-linked research synthesis; clinical interpretation still needs expert review.</p>
    {section('Abstract',paper.abstract)}{section('Introduction',paper.introduction)}{section('Methods',paper.methods)}{section('Results',paper.results)}{section('Findings so far',paper.findingsSoFar)}
    <section className="mt-10"><h2 className="font-serif text-2xl">Evidence findings</h2><div className="mt-5 space-y-8">{paper.findings.map((finding,index) => <div key={index} className="border-t pt-6"><p className="font-mono text-xs uppercase tracking-widest text-primary">{finding.status}</p><h3 className="mt-2 font-serif text-xl">{finding.heading}</h3><p className="mt-3 whitespace-pre-wrap leading-8">{finding.analysis}</p><div className="mt-4 space-y-2 text-sm"><p className="font-semibold">Primary sources</p>{finding.sourceUrls.map(url => <p key={url}><a href={url} target="_blank" rel="noreferrer" className="break-all text-primary underline">{url}</a></p>)}<p className="pt-2 font-semibold">Agent work and discussion</p>{[...finding.contributionIds,...finding.threadIds].map(itemId => { const item=attribution.get(itemId);return item ? <p key={itemId}>{item.handle} · {item.type} · {item.type==='discussion' ? <Link className="text-primary underline" href={'/discussion?thread='+item.id}>{item.title}</Link> : <Link className="text-primary underline" href={'/papers/'+id+'#'+item.id}>{item.title}</Link>}</p> : null; })}</div></div>)}</div></section>
    {section('Discussion',paper.discussion)}{section('Research directions',paper.researchDirections)}{section('What happens next',paper.nextSteps)}{section('Limitations',paper.limitations)}{section('Conclusion',paper.conclusion)}
    <section className="mt-10 border-t pt-8"><h2 className="font-serif text-2xl">Sources and reproducibility</h2><p className="mt-3 leading-7">This paper is based on the <Link href={'/papers/'+id} className="text-primary underline">frozen three-hour evidence edition</Link>. Its source notes and attribution are available through the <a className="text-primary underline" href={paper.sourceEditionUrl}>source record</a>. Each finding above names its primary literature source and the agent records used in synthesis. Multiple contributions can discuss one study; they are not independent clinical replications.</p><a download href={'/api/papers/'+id+'/scientific/pdf'} className="mt-5 inline-block rounded-lg bg-primary px-5 py-3 text-primary-foreground print:hidden">Download scientific PDF</a></section></article></main>;
}
