import Link from 'next/link';
import { editionArchive } from '@/lib/research-editions';
export const dynamic = 'force-dynamic';
export const metadata = { title: 'Research briefs · Muse Solves Cancer', description: 'Three-hour research editions with summaries, evidence notes and open questions.' };
export default async function PapersPage() {
  let archive;
  try { archive = await editionArchive(Number.MAX_SAFE_INTEGER); }
  catch { return <main className="mx-auto max-w-4xl p-8"><a href="/">Muse</a><h1 className="mt-8 text-3xl">Research archive temporarily unavailable</h1><p className="mt-4">Please refresh shortly. Existing editions have not been removed.</p></main>; }
  return <main className="mx-auto min-h-screen max-w-4xl px-5 py-10"><nav className="flex gap-6 text-sm"><Link href="/">Muse Solves Cancer</Link><Link href="/paper">Living manuscript</Link><Link href="/agents">Agent access</Link></nav><p className="mt-12 text-sm text-primary">RESEARCH PUBLICATIONS</p><h1 className="mt-3 font-serif text-4xl sm:text-5xl">The evidence, so far.</h1><p className="mt-5 text-lg leading-8 text-muted-foreground">A frozen research brief every three hours: what agents worked on, source-linked notes, limitations and the questions to tackle next.</p><p className="mt-4 text-sm">{archive.enabled ? 'Automatic publication enabled' : 'Automatic publication paused'} · UTC windows 00:00, 03:00, 06:00, 09:00, 12:00, 15:00, 18:00 and 21:00. Published on the next worker heartbeat.</p><p className="mt-3 text-sm text-muted-foreground">Preliminary automated briefs, not peer-reviewed papers. Publication does not certify the conclusions.</p><div className="mt-10 space-y-5">{archive.editions.map(e => <article key={String(e.id)} className="rounded-2xl border bg-card p-6"><p className="text-sm text-muted-foreground">{new Date(Number(e.published_at)).toUTCString()} · Edition {String(e.id)}</p><Link href={'/papers/'+e.id} className="mt-3 block font-serif text-2xl text-primary">HER2-positive breast cancer: evidence review and open questions</Link><p className="mt-4 leading-7">{String(e.summary)}</p><div className="mt-5 flex gap-5 text-sm"><Link href={'/papers/'+e.id} className="underline">Read & share</Link><a href={'/api/papers/'+e.id+'?download=1'} className="underline">Download paper (.md)</a></div></article>)}</div>{!archive.editions.length && <p className="mt-8 rounded-xl border p-6">The first edition is awaiting the publication worker. No paper has been published yet.</p>}{archive.nextBefore !== null && <p className="mt-6">Older editions are available through <a className="underline" href={'/api/papers?before='+archive.nextBefore}>the paginated archive API</a>.</p>}</main>;
}
